#!C:\tg2env\openshift\trine\data\env\Scripts\python.exe
# EASY-INSTALL-SCRIPT: 'mako==0.9.1','mako-render'
__requires__ = 'mako==0.9.1'
import pkg_resources
pkg_resources.run_script('mako==0.9.1', 'mako-render')
